let suggestions = [
    "18 Again (Tagalog Dubbed)",
    "One The Woman  (Tagalog Dubbed)",
    "Now, We Are Breaking Up  (Tagalog Dubbed)",
    "Voice Season 1 (Tagalog Dubbed)",
    "Voice Season 2 (Tagalog Dubbed)",
    "Clean with Passion for Now (Tagalog Dubbed)",
    "Tale of the Nine Tailed (Tagalog Dubbed)",
    "Moon Lovers Scarlet Heart Ryeo (Tagalog Dubbed)",
    "The Devil Judge (Tagalog Dubbed)",
    "The Penthouse (Tagalog Dubbed)",
    "When the Weather Is Fine (Tagalog Dubbed)",
    "Oh My Baby (Tagalog Dubbed)",
    "Reply 1988 (Tagalog Dubbed)",
    "What's Wrong with Secretary Kim? (Tagalog Dubbed)",
    "Lie After Lie (Tagalog Dubbed)",
    "The Red Sleeve (Tagalog Dubbed)",
    "Lovers of the Red Sky (Tagalog Dubbed)",
    "Pinocchio (Tagalog Dubbed)",
    "Prison Playbook (Tagalog Dubbed)",
    "L.U.C.A. The Beginning (Tagalog Dubbed)",
    "Sell Your Haunted House (Tagalog Dubbed)",
    "She Was Pretty (Tagalog Dubbed)",
    "Doom at Your Service (Tagalog Dubbed)",
    "Beyond Evil (Tagalog Dubbed)",
    "The Beauty Inside (Tagalog Dubbed)",
    "True Beauty (Tagalog Dubbed)",
    "Welcome to Waikiki (Tagalog Dubbed)",
    "One Ordinary Day (Tagalog Dubbed)",
    "Encounter (Tagalog Dubbed)",
    "Taxi Driver (Tagalog Dubbed)",
    "River Where the Moon Rises (Tagalog Dubbed)",
    "Zombie Detective (Tagalog Dubbed)",
    "Another Miss Oh (Tagalog Dubbed)",
    "Hotel Del Luna (Tagalog Dubbed)",
    "Emergency Couple (Tagalog Dubbed)",
    "W (Tagalog Dubbed)",
    "Lawless Lawyer (Tagalog Dubbed)",
    "The Secret Life of My Secretary (Tagalog Dubbed)",
    "Iljimae (Tagalog Dubbed)",
];
